spring:
  batch:
#    job:
#      enabled: false
    initialize-schema: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-batch;MODE=MYSQL
    username: 'sa'
    password:
    initialization-mode: always
#      continue-on-error: true


#spring.datasource.url=jdbc:h2:tcp://localhost/~/spring-batch
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.batch.initialize-schema=always
#
#spring.batch.job.enabled=false